# U - Universal Constants
import pygame

ASTEROID_DELAY = 4
ASTEROID_SPEED = pygame.Vector2(100,0)
ASTEROID_TIMER_STOPPED = -9999
SCREEN_SIZE = 768
CENTER = pygame.Vector2(SCREEN_SIZE/2, SCREEN_SIZE/2)
SAFE_EMERGENCE_DISTANCE = 100
SHIP_ACCELERATION = pygame.Vector2(120, 0)
SHIP_EMERGENCE_TIME = 3
SHIP_ROTATION_STEP = 120
SPEED_OF_LIGHT = 500
MISSILE_SPEED = SPEED_OF_LIGHT/3
MISSILE_LIFETIME = 3
MISSILE_LIMIT = 4
