# U - Universal Constants
import pygame

ASTEROID_SPEED = pygame.Vector2(100,0)
SCREEN_SIZE = 768
CENTER = pygame.Vector2(SCREEN_SIZE/2, SCREEN_SIZE/2)
SHIP_ACCELERATION = pygame.Vector2(120, 0)
SHIP_ROTATION_STEP = 120
SPEED_OF_LIGHT = 500
MISSILE_SPEED = SPEED_OF_LIGHT/3
